print("Input")
Nama = input("Input Nama           :")
NIM = input("NIM                  :")
Kelas_Paralel = input("Kelas Paralel        :")
Tempat_TanggalLahir = input("Tempat Tanggal Lahir :")
Alamat = input("Alamat               :")
Hobby = input("Hobby                :")
NoHp = input("No HP                :")

print("\nOutput")
print("Input Nama           :", Nama)
print("NIM                  :", NIM)
print("Kelas Paralel        :", Kelas_Paralel)
print("Tempat/Tanggal Lahir :", Tempat_TanggalLahir)
print("Alamat               :", Alamat)
print("Hobby                :", Hobby)
print("NO.Hp                :", NoHp)